### PR TITLE
Attempt to switch logging to Go standard slog SDK logging

### PR DESCRIPTION
**Pull request by pete-woods**
A possibly incomplete attempt to migrate the logging over to the now standard Go `slog` system.

I see one of the dependencies (holster) still using logrus, though...

### CODE REVIEW

**Comment by thrawn01** [comment]
Awesome! thank you for contributing this PR. We need to set a date for V3 release. I'll resolve some conflicts and see where we are at. I've been busy with https://github.com/kapetan-io/querator/ and a few other projects.

**Comment by pete-woods** [comment]
Okay, I've rebased, and made the linter happy locally, at least

**Comment by thrawn01** [comment]
I'm working on a PR to remove holster now, I'll merge this one first then rebase.

**Comment by pete-woods** [comment]
Woo! Thanks! :D

**Pull request merged**
